### ISSUE TITLE
The Download Links Don't Work

### ISSUE THREAD

**Issue by OusmBlueNinja** [SigmaJello/Archive#1]
the domains apear to have been sold

**Comment by cherrypluck** [comment]
> the domains apear to have been sold

all .ga domains were suspended and are no longer available.
I've temporarily moved the archive over to a subdomain under my personal site (i'll make use of this repository when I have time)

For the time being, use **[jello.cherri.cf](https://jello.cherri.cf)** to access the archive.
If you need any further updates, feel free to join the _[discord server](https://discord.gg/sigma-archives-989789190692675615)_

- Cherry
